services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080" # optional direct port
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  keycloak:
    driver: bridge

volumes:
  keycloak_data:
