services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "${TRAEFIK_PORT}:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: ${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080" # optional direct port
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  keycloak:
    driver: bridge

volumes:
  keycloak_data: